#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'vpk'

def options(opt):
	# stub
	return

def configure(conf):
	conf.define('PROTECTED_THINGS_DISABLE',1)

def build(bld):
	source = ['packtest.cpp']
	includes = ['.', '../../public', '../../public/tier0', '../common']
	defines = []
	libs = ['tier2', 'tier1', 'tier0', 'vpklib', 'vstdlib', 'bitmap', 'mathlib']

	if bld.env.DEST_OS != 'win32':
		libs += [ 'DL', 'LOG' ]
	else:
		bld.env.LDFLAGS += ['/subsystem:console']
		libs += ['USER32', 'SHELL32']

	install_path = bld.env.BINDIR
	bld(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx cxxprogram',
		includes = includes,
		defines  = defines,
		use      = libs,
		install_path = install_path,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)
