#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'hammer'

def options(opt):
	opt.load('compiler_cxx qt5')

def configure(conf):
	conf.want_qt6 = True
	conf.load('compiler_cxx qt5')

def build(bld):
	source = [
		'widgets/ModelView.cpp',
		'widgets/Map2DView.cpp',
		'widgets/Map3DView.cpp',
		'main.cpp',
		'MainWindow.cpp',
		'MapDocument.cpp',
		'FgdManager.cpp',
		'VmfIO.cpp',
    ]

	headers = [
		'widgets/ModelView.h',
		'widgets/Map2DView.h',
		'widgets/Map3DView.h',
		'MainWindow.h',
	]

	includes = [
        '.',
		'../../materialsystem',
		'../../public',
		'../../public/tier0',
		'../../public/tier1',
		'../../public/tier2',
		'../../thirdparty/SDL',
	]

	defines = ['SW_HAMMER_TOOL']

	libs = ['QT6CORE', 'QT6WIDGETS', 'QT6GUI', 'fgdlib', 'appframework', 'mathlib', 'bitmap', 'vstdlib', 'tier2', 'tier1', 'tier0', 'togl', 'SDL2']

	install_path = bld.env.BINDIR

	bld(
		source   = source,
		moc  = headers,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'cxx cxxprogram qt6',
		includes = includes,
		defines  = defines,
		use      = libs,
		install_path = install_path,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)
