#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'bsppack'

def options(opt):
	# stub
	return

def configure(conf):
	conf.define('PROTECTED_THINGS_DISABLE',1)

def build(bld):
	source = [
        '../common/bsplib.cpp',
        'bsppack.cpp',
		'../common/cmdlib.cpp',
		'../../public/filesystem_helpers.cpp',
        '../../public/filesystem_init.cpp',
        '../common/filesystem_tools.cpp',
		'../../public/lumpfiles.cpp',
		'../common/scriplib.cpp',
		'../../public/zip_utils.cpp',
		'../../filesystem/linux_support.cpp',
    ]
	includes = ['.', '../../public', '../../public/tier0', '../../public/tier1', '../common']
	defines = []
	libs = ['lzma', 'mathlib', 'vstdlib', 'tier2', 'tier1', 'tier0']

	install_path = bld.env.LIBDIR
	bld.shlib(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx',
		includes = includes,
		defines  = defines,
		use      = libs,
		install_path = install_path,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)
