#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'gizmo'

def options(opt):
	# stub
	return

def configure(conf):
	# stub
	return

def build(bld):
	source = [
        'ImGuizmo.cpp',
        'GraphEditor.cpp',
        'ImCurveEdit.cpp',
        'ImGradient.cpp',
        'ImSequencer.cpp',
        'ImVectorEditor.cpp',
	]

	includes = [
        '.',
		'../../imgui',
        '../thirdparty/stb',
	]

	defines = []

	libs = []
		
	bld.stlib(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx',
		includes = includes,
		defines  = defines,
		use      = libs,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)

