#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'studiomdl'

def options(opt):
	# stub
	return

def configure(conf):
	conf.define('PROTECTED_THINGS_DISABLE',1)

def build(bld):
	source = [
        '../../public/bone_setup.cpp',
        '../common/cmdlib.cpp',
        'collisionmodel.cpp',
        '../../public/collisionutils.cpp',
        'dmxsupport.cpp',
        '../../public/filesystem_helpers.cpp',
        '../../public/filesystem_init.cpp',
        '../common/filesystem_tools.cpp',
        'hardwarematrixstate.cpp',
        'hardwarevertexcache.cpp',
        '../../public/interpolatortypes.cpp',
        #'../../public/mdlobjects/mdlobjects.cpp',
        '../../public/phonemeconverter.cpp',
        '../../public/movieobjects/movieobjects_compiletools.cpp',
        'mrmsupport.cpp',
        'objsupport.cpp',
        'optimize.cpp',
        'perfstats.cpp',
        '../common/physdll.cpp',
        '../common/scriplib.cpp',
        'simplify.cpp',
        '../../public/studio.cpp',
        '../../common/studiobyteswap.cpp',
        'studiomdl.cpp',
        'UnifyLODs.cpp',
        'v1support.cpp',
        'write.cpp',
        'checkuv.cpp',
    ]

	includes = [
        '.', '../../public', 
        '../../public/tier0', 
        '../../public/tier1', 
        '../common',
        '../nvtristriplib',
    ]

	defines = ['PROTECTED_THINGS_DISABLE']

	libs = [
        'appframework', 
        'datamodel', 
        'dmserializers', 
        'mdlobjects', 
        'movieobjects', 
        'nvtristrip', 
        'mathlib', 
        'vstdlib',
        'tier3',
        'tier2',
        'tier1',
        'tier0',
    ]

	install_path = bld.env.BINDIR
	bld(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx cxxprogram',
		includes = includes,
		defines  = defines,
		use      = libs,
		install_path = install_path,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)
