#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'mdlobjects'

def options(opt):
	# stub
	return

def configure(conf):
	return

def build(bld):
	source = [
		'dmebodygroup.cpp',
        'dmebodygrouplist.cpp',
        'dmecollisionmodel.cpp',
        'dmehitbox.cpp',
        'dmehitboxset.cpp',
        'dmebodypart.cpp',
        'dmeblankbodypart.cpp',
        'dmelod.cpp',
        'dmelodlist.cpp',
        'dmemdllist.cpp',
        'dmeboneweight.cpp',
        'dmebonemask.cpp',
        'dmebonemasklist.cpp',
        'dmesequence.cpp',
        'dmesequencelist.cpp',
        'dmeboneflexdriver.cpp',
	]

	includes = ['.', '../public', '../public/tier0', '../public/tier1', '../utils/common']
	defines = []
	libs = []

	bld.stlib(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx',
		includes = includes,
		defines  = defines,
		use      = libs,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)

