#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'glview'

def options(opt):
	# stub
	return

def configure(conf):
	conf.define('PROTECTED_THINGS_DISABLE',1)

def build(bld):
	source = [
        '../common/cmdlib.cpp',
        '../../public/filesystem_helpers.cpp',
        '../../public/filesystem_init.cpp',
        '../common/filesystem_tools.cpp',
        '../common/physdll.cpp',
        'glview.cpp',
    ]

	includes = ['.', '../../public', '../../public/tier0', '../../public/tier1', '../common']

	defines = ['PROTECTED_THINGS_DISABLE']

	local_libs = ['vstdlib', 'mathlib', 'tier2', 'tier1', 'tier0']

    #system_libs = ['GL', 'GLU', 'X11', 'm']

	install_path = bld.env.BINDIR
	bld(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx cxxprogram',
		includes = includes,
		defines  = defines,
		use      = local_libs,     # Internal project static/shared models
		lib      = ['GL', 'GLU', 'X11', 'm'],    # Appends -lGL -lGLU -lX11 -lm at the absolute end of the command line
		install_path = install_path,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)
