#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'vbspinfo'

def options(opt):
	# stub
	return

def configure(conf):
	conf.define('DONT_PROTECT_FILEIO_FUNCTIONS',1)

def build(bld):
	source = [
        'vbspinfo.cpp',
        '../common/tools_minidump.cpp',
        '../common/bsplib.cpp',
        '../common/cmdlib.cpp',
        '../../public/filesystem_helpers.cpp',
        '../../public/filesystem_init.cpp',
        '../common/filesystem_tools.cpp',
        '../../public/lumpfiles.cpp',
        '../../public/scratchpad3d.cpp',
        '../common/scriplib.cpp',
        '../../public/zip_utils.cpp',
    ]
	includes = ['.', '../../public', '../../public/tier0', '../../public/tier1', '../common']
	defines = []
	libs = [
        'tier2', 
        'tier1', 
        'tier0', 
        'lzma', 
        'vstdlib', 
        'bitmap', 
        'mathlib'
    ]

	install_path = bld.env.BINDIR
	bld(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx cxxprogram',
		includes = includes,
		defines  = defines,
		use      = libs,
		install_path = install_path,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)
