#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'imhammer'

def options(opt):
	# stub
	return

def configure(conf):
	# stub
	return

def build(bld):
	source = [
        'main.cpp',
    ]

	includes = [
        '.',
		'../../imgui',
        '../libgizmo',
        #'../../thirdparty/stb',
		'../../public',
		'../../public/tier0',
		'../../public/tier1',
	]

	defines = []

	libs = ['fgdlib', 'tier1', 'tier0', 'imgui', 'gizmo', 'X11', 'GL']

	install_path = bld.env.BINDIR
	bld(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx cxxprogram',
		includes = includes,
		defines  = defines,
		use      = libs,
		install_path = install_path,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)
