#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'vbsp'

def options(opt):
	# stub
	return

def configure(conf):
	conf.define('PROTECTED_THINGS_DISABLE',1)

def build(bld):
	source = [
        'boundbox.cpp',
        'brushbsp.cpp',
        '../../public/collisionutils.cpp',
        'csg.cpp',
        'cubemap.cpp',
        'detail.cpp',
        'detailobjects.cpp',
        '../../public/disp_common.cpp',
        '../../public/disp_powerinfo.cpp',
        'ivp.cpp',
        'disp_ivp.cpp',
        'disp_vbsp.cpp',
        'faces.cpp',
        'glfile.cpp',
        'leakfile.cpp',
        '../../public/loadcmdline.cpp',
        '../../public/lumpfiles.cpp',
        'map.cpp',
        'manifest.cpp',
        'materialpatch.cpp',
        'materialsub.cpp',
        '../common/mstristrip.cpp',
        'nodraw.cpp',
        'normals.cpp',
        'overlay.cpp',
        '../common/physdll.cpp',
        'portals.cpp',
        'prtfile.cpp',
        '../../public/scratchpad3d.cpp',
        '../common/scratchpad_helpers.cpp',
        'staticprop.cpp',
        'textures.cpp',
        'tree.cpp',
        '../common/utilmatlib.cpp',
        'vbsp.cpp',
        'worldvertextransitionfixup.cpp',
        'writebsp.cpp',
        '../../public/zip_utils.cpp',
    ]

    # Common Files
	source += [
        '../common/bsplib.cpp',
        '../../public/builddisp.cpp',
        '../../public/chunkfile.cpp',
        '../common/cmdlib.cpp',
        '../../public/filesystem_helpers.cpp',
        '../../public/filesystem_init.cpp',
        '../common/filesystem_tools.cpp',
        '../common/map_shared.cpp',
        '../common/pacifier.cpp',
        '../common/polylib.cpp',
        '../common/scriplib.cpp',
        '../common/threads.cpp',
        #'../common/strlwr.cpp',
        '../../filesystem/linux_support.cpp',
        '../common/tools_minidump.cpp',
    ]

	includes = [
        '.', '../../public', 
        '../../public/tier0', 
        '../../public/tier1', 
        '../../external/vpc/public', 
        '../common',
        '../../thirdparty/SDL',
    ]

	defines = ['MACRO_MATHLIB', 'PROTECTED_THINGS_DISABLE']

	libs = [
        'tier2', 
        'tier1', 
        'tier0', 
        'fgdlib', 
        'vtf', 
        'vpklib', 
        'vstdlib', 
        'bitmap', 
        'mathlib',
        'lzma'
    ]

	if bld.env.DEST_OS != 'win32':
		libs += [ 'DL', 'LOG' ]
	else:
		bld.env.LDFLAGS += ['/subsystem:console']
		libs += ['USER32', 'SHELL32']

	install_path = bld.env.BINDIR
	bld(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx cxxprogram',
		includes = includes,
		defines  = defines,
		use      = libs,
		install_path = install_path,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)
