#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'nvtristrip'

def options(opt):
	# stub
	return

def configure(conf):
	return

def build(bld):
	source = [
		'nvtristrip.cpp',
		'nvtristripobjects.cpp',
		#'vertexcache.cpp',
	]

	includes = ['.', '../../public', '../../public/tier0', '../../public/tier1', '../utils/common']
	defines = []
	libs = []

	bld.stlib(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx',
		includes = includes,
		defines  = defines,
		use      = libs,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)

