#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'bspzip'

def options(opt):
	# stub
	return

def configure(conf):
	conf.define('ZIP_SUPPORT_LZMA_ENCODE',1)

def build(bld):
	source = [
        '../common/bsplib.cpp',
        'bspzip.cpp',
        '../common/cmdlib.cpp',
        '../../public/filesystem_helpers.cpp',
        '../../public/filesystem_init.cpp',
        '../common/filesystem_tools.cpp',
        '../../public/lumpfiles.cpp',
        '../common/scriplib.cpp',
        '../../public/zip_utils.cpp',
    ]
	includes = ['.', '../../public', '../../public/tier0', '../../public/tier1', '../common']
	defines = ['MACRO_MATHLIB', 'PROTECTED_THINGS_DISABLE', 'ZIP_SUPPORT_LZMA_ENCODE']
	libs = ['lzma', 'mathlib', 'vstdlib', 'tier2', 'tier1', 'tier0']

	install_path = bld.env.BINDIR
	bld(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx cxxprogram',
		includes = includes,
		defines  = defines,
		use      = libs,
		install_path = install_path,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)
